# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35ed47fba687bd8b9bc6902e7f57deb4a016095ebdca9723f495067b184cd256ea1f7b299025bee0fcf9f5c9bd18e8e59f13818f285d97bbbe45cb56dfe2a7be

test:
  secret_key_base: dfb132a2751ca8918f3579bcd3c1ad8ce93d7d698e745af7b1def1301e4b28e5369258a00eb3be02713a37922c5cca7e556f28764a9cd2c9914a5399d15ef6b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
